name: localhost-ci

on:
  pull_request:
    branches:
      - prod
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: 'setup node: ${{ matrix.node-version }} platform: ${{ matrix.os }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with Yarn
        run: yarn install

      - name: Install localhost
        run: |
          npm link;
          yarn link

      - name: Run Tests
        run: yarn run test
